# Generated by Django 4.2.20 on 2025-04-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitte', '0003_alter_ad_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('dark', 'Темная'), ('light', 'Светлая')], default='light', max_length=5),
        ),
    ]
